name: template
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - black
  - flake8
  - pre-commit
  - pip
  - pytest
  - kaggle
  - tensorflow
  - pip:
    - tensorflow-object-detection-api
    - pycodestyle 
    - pycodestyle_magic
    - pandas

  